{% set name = "optype" %}
{% set version = "0.9.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/optype-{{ version }}.tar.gz
  sha256: d7487a5b7fe96bacfc5dc8fab6b90c14f1e65e7ba6e7b22a8bef48d29690edac

build:
  skip: true  # [py<310]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - hatchling
    - pip
  run:
    - python
    - typing-extensions >=4.10  # [py<313]

test:
  imports:
    - optype
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jorenham/optype/
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Building blocks for precise & flexible type hints
  description: Opinionated typing package for developing beautifully accurate typing annotations, compatible with both static- and runtime type-checkers, and is battle-tested. OpType has (optional) NumPy typing tools for annotating shape-typed array-likes of with specific dtype, dtype-likes, and much more.
  dev_url: https://github.com/jorenham/optype/
  doc_url: https://github.com/jorenham/optype/blob/master/README.md

extra:
  recipe-maintainers:
    - lucascolley
    - jorenham
