schema_version: 1

context:
  name: optype
  version: "0.12.2"
  python_min: "3.11"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/optype-${{ version }}.tar.gz
  sha256: 3f53a89f56f0ea23be4d212611dce0f3a2a8946543a9a72783e349c49b232934

build:
  number: 0
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  noarch: python

requirements:
  host:
    - python ${{ python_min }}.*
    - uv-build
    - pip
  run:
    - python >=${{ python_min }}
    # needed for python <3.13, not using a selector to enable noarch
    - typing-extensions >=4.10 

tests:
  - python:
      imports:
        - optype
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Building blocks for precise & flexible type hints
  description: Opinionated typing package for developing beautifully accurate typing annotations, compatible with both static- and runtime type-checkers, and is battle-tested. OpType has (optional) NumPy typing tools for annotating shape-typed array-likes of with specific dtype, dtype-likes, and much more.
  homepage: https://github.com/jorenham/optype/
  repository: https://github.com/jorenham/optype/
  documentation: https://github.com/jorenham/optype/blob/master/README.md

extra:
  recipe-maintainers:
    - lucascolley
    - jorenham
