schema_version: 1

context:
  name: optype
  version: "0.10.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/optype-${{ version }}.tar.gz
  sha256: 2b89a1b8b48f9d6dd8c4dd4f59e22557185c81823c6e2bfc43c4819776d5a7ca

build:
  number: 0
  skip: match(python, "<3.11")
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
  host:
    - python
    - hatchling
    - pip
  run:
    - python
    - if: match(python, "<3.13")
      then: typing-extensions >=4.10

tests:
  - python:
      imports:
        - optype
  - requirements:
      run:
        - pip
    script:
      - pip check

about:
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Building blocks for precise & flexible type hints
  description: Opinionated typing package for developing beautifully accurate typing annotations, compatible with both static- and runtime type-checkers, and is battle-tested. OpType has (optional) NumPy typing tools for annotating shape-typed array-likes of with specific dtype, dtype-likes, and much more.
  homepage: https://github.com/jorenham/optype/
  repository: https://github.com/jorenham/optype/
  documentation: https://github.com/jorenham/optype/blob/master/README.md

extra:
  recipe-maintainers:
    - lucascolley
    - jorenham
